[package]
name = "atp-tools-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
atp-tools-bsky = { path = "../bsky" }
atp-tools-core = { path = "../core" }
atp-tools-margin = { path = "../margin" }
clap.workspace = true
owo-colors.workspace = true
serde_json.workspace = true
tokio.workspace = true
