[package]
name = "atp-tools-api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
atp-tools-bsky = { path = "../bsky" }
atp-tools-core = { path = "../core" }
serde.workspace = true
clap.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "signal", "sync"] }

axum = "0.8.9"
chrono = { version = "0.4.42", default-features = false, features = ["clock", "std"] }
futures-util = "0.3.31"
tokio-rusqlite = "0.7.0"
tokio-tungstenite = { version = "0.29.0", features = ["rustls-tls-webpki-roots"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[build-dependencies]
clap.workspace = true
clap_mangen = "0.3"
shell-escape = "0.1"
